### PR TITLE
Introducing retained flag in modules so they are retained even when the component is unmounted

### PR DESCRIPTION
**Pull request by navneet-g**
@ahrnee I have introduced a retained flag in IModule that is respected by the RefCounter to keep the module for infinity.  This is an alternate implementation to #86

### CODE REVIEW

**Comment by ryanf5** [comment]
Hey Navneet, thanks for providing this great feature. I'm wondering when this will be released so I can use it in my project?

**Comment by navneet-g** [comment]
@ryanf5  we had some permission issues with some packages. They are resolved today, I will publish new packages shortly.

**Comment by navneet-g** [comment]
@ryanf5  Please try version 4.0.1 and let me know if you see any issues.

**Comment by ryanf5** [comment]
@navneet-g Works like a charm, thanks!

**Pull request merged**
